
development:
  adapter: 'mysql2'
  host:     <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  database: <%= ENV['MYSQL_DB'] %>
  port:     <%= ENV['MYSQL_PORT'] %>


staging:
  adapter: 'mysql2'
  host:     <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  database: <%= ENV['MYSQL_DB'] %>
  port:     <%= ENV['MYSQL_PORT'] %>

production:
  adapter: 'mysql2'
  host:     <%= ENV['MYSQL_HOST'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASS'] %>
  database: <%= ENV['MYSQL_DB'] %>
  port:     <%= ENV['MYSQL_PORT'] %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 8
